apiVersion: v1
kind: ConfigMap
metadata:
    name: thanos-objstore-s3-config
data:
    s3.yml: |
        type: S3
        config:
            bucket: "def"
            endpoint: "10.8.1.73:10110"
            access_key: "adsf"
            secret_key: "ddf"
            insecure: true
